// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvlbkwqzgdtgptybjuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdmxia3dxemdkdGdwdHlianV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTM4MTYsImV4cCI6MjA2NjAyOTgxNn0.6ewYItGtesu9JnQlwJcLeUqUiFztL49eQtWaiycguhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});